name: ar_model_viewer
description: A new Flutter AR application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencias para AR
  ar_flutter_plugin: ^0.7.3
  permission_handler: ^10.4.5  # Versión compatible con ar_flutter_plugin
  file_picker: ^5.3.1

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Aquí puedes agregar tus modelos 3D
  assets:
    - assets/models/